# Use a minimal base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file if you have one
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8080



# Command to run the application
CMD ["python", "cachingproxyserver.py"]